// <auto-generated />
namespace RealtorsOffice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class alltables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alltables));
        
        string IMigrationMetadata.Id
        {
            get { return "202003111718522_all tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
